// <auto-generated />
namespace Marketing.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Store1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Store1));
        
        string IMigrationMetadata.Id
        {
            get { return "201611191234136_Store1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
